[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.10.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  #version = "0.11.7"
  branch = "v0.12-dev"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.38.1"

[prune]
  go-tests = true
  unused-packages = true
